# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J42MEkpLH7b21kdkbIlxT4PNP_qYbpf5
"""

import pandas as pd
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.metrics import f1_score, confusion_matrix

def classify_wine_quality(df_train: pd.DataFrame, df_test: pd.DataFrame) -> dict:

    # Variables predictoras
    features = [
        "alcohol",
        "acidity",
        "sugar",
        "ph",
        "sulphates",
        "density"
    ]

    # Separar variables y etiquetas
    X_train = df_train[features]
    y_train = df_train["quality"]

    X_test = df_test[features]
    y_test = df_test["quality"]

    # Pipeline solicitado
    pipeline = Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler()),
        ("clf", GradientBoostingClassifier(
            n_estimators=100,
            random_state=42
        ))
    ])

    # Entrenar modelo
    pipeline.fit(X_train, y_train)

    # Predicciones
    predictions = pipeline.predict(X_test)

    # Probabilidades de clase positiva
    probabilities = pipeline.predict_proba(X_test)[:, 1]

    # Métricas
    f1 = f1_score(y_test, predictions)

    cm = confusion_matrix(y_test, predictions)

    # Resultado final
    return {
        "predictions": predictions,
        "probabilities": probabilities,
        "f1_score": f1,
        "confusion_matrix": cm
    }