# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nS1oYBgK4JtQ3L48YuKi_xwT2Y51X2gK
"""

import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression

# Función objetivo
def class_accuracy(X: pd.DataFrame, y: np.ndarray) -> np.ndarray:
    model = LogisticRegression(max_iter=1000)
    model.fit(X, y)

    y_pred = model.predict(X)

    clases = np.unique(y)
    accuracies = []

    for c in clases:
        idx = (y == c)
        correct = np.sum(y_pred[idx] == y[idx])
        total = np.sum(idx)
        accuracies.append(correct / total)

    return np.array(accuracies)


# Función generadora
def generar_caso_de_uso_preparar_datos():
    np.random.seed(None)  # aleatorio

    # Tamaños aleatorios
    n_samples = np.random.randint(60, 150)
    n_features = np.random.randint(2, 6)
    n_classes = np.random.randint(2, 5)

    # Datos
    X = pd.DataFrame(
        np.random.randn(n_samples, n_features),
        columns=[f'feature_{i}' for i in range(n_features)]
    )

    # Crear etiquetas con cierta estructura (no totalmente aleatorio)
    weights = np.random.randn(n_features, n_classes)
    scores = X.values @ weights
    y = np.argmax(scores, axis=1)

    # Input
    input_data = {
        "X": X,
        "y": y
    }

    # Output esperado
    output_data = class_accuracy(X, y)

    return input_data, output_data

input_data, output_data = generar_caso_de_uso_preparar_datos()

print("=== INPUT ===")
print(input_data["X"].head())
print("\ny:", input_data["y"][:10])

print("\n=== OUTPUT ===")
print("Exactitud por clase:", output_data)

# Ver qué clase corresponde a cada valor
print("\nClases:", np.unique(input_data["y"]))