# -*- coding: utf-8 -*-
"""Untitled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a7pmnuCXA0b6KInlAi8gHYJ4FsNBipyA
"""

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.inspection import permutation_importance

# Función objetivo (la que queremos testear)
def permutation_importance_mean(X: pd.DataFrame, y: np.ndarray, n_repeats: int) -> np.ndarray:
    model = RandomForestClassifier(random_state=42)
    model.fit(X, y)

    result = permutation_importance(model, X, y, n_repeats=n_repeats, random_state=42)

    return result.importances_mean


# Función solicitada
def generar_caso_de_uso_preparar_datos_0001():
    # Componente aleatorio
    np.random.seed(None)

    # Generar dimensiones aleatorias
    n_samples = np.random.randint(50, 150)
    n_features = np.random.randint(3, 8)

    # Generar datos aleatorios
    X = pd.DataFrame(
        np.random.randn(n_samples, n_features),
        columns=[f'feature_{i}' for i in range(n_features)]
    )

    # Variable objetivo binaria
    y = np.random.randint(0, 2, size=n_samples)

    # Número de repeticiones aleatorio
    n_repeats = np.random.randint(3, 10)

    # Construir input
    input_data = {
        "X": X,
        "y": y,
        "n_repeats": n_repeats
    }

    # Calcular output esperado
    output_data = permutation_importance_mean(X, y, n_repeats)

    return input_data, output_data

input_data, output_data = generar_caso_de_uso_preparar_datos()

print("=== INPUT ===")
print("X (primeras filas):")
print(input_data["X"].head())

print("\ny (primeros valores):")
print(input_data["y"][:10])

print("\nn_repeats:")
print(input_data["n_repeats"])

print("\n=== OUTPUT ===")
print("Importancia promedio por variable:")
print(output_data)
