# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kXB3Y-ZuqNzqZQyhyh3QdE7kUi1ZTpxR
"""

import numpy as np
import pandas as pd
from sklearn.cluster import KMeans

# Función objetivo
def mean_cluster_distance(X: pd.DataFrame, k: int) -> float:
    model = KMeans(n_clusters=k, random_state=42, n_init=10)
    model.fit(X)

    # Obtener etiquetas y centroides
    labels = model.labels_
    centroids = model.cluster_centers_

    # Calcular distancias
    distances = []

    for i in range(len(X)):
        punto = X.iloc[i].values
        centroide = centroids[labels[i]]
        dist = np.linalg.norm(punto - centroide)  # distancia euclidiana
        distances.append(dist)

    return float(np.mean(distances))


# Función generadora
def generar_caso_de_uso_preparar_datos():
    np.random.seed(None)  # aleatorio

    # Dimensiones aleatorias
    n_samples = np.random.randint(50, 150)
    n_features = np.random.randint(2, 5)
    k = np.random.randint(2, 6)

    # Generar datos con cierta estructura de clusters
    X_list = []
    for _ in range(k):
        centro = np.random.randn(n_features) * 5
        puntos = centro + np.random.randn(n_samples // k, n_features)
        X_list.append(puntos)

    X_array = np.vstack(X_list)

    # Convertir a DataFrame
    X = pd.DataFrame(
        X_array,
        columns=[f'feature_{i}' for i in range(n_features)]
    )

    # Input
    input_data = {
        "X": X,
        "k": k
    }

    # Output esperado
    output_data = mean_cluster_distance(X, k)

    return input_data, output_data

input_data, output_data = generar_caso_de_uso_preparar_datos()

print("=== INPUT ===")
print(input_data["X"].head())
print("\nk:", input_data["k"])

print("\n=== OUTPUT ===")
print("Distancia promedio al centroide:", output_data)