# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y0CY2DMcng6qm45_MyVCzhUk19wNW5w8
"""

import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import KFold
from sklearn.metrics import mean_squared_error

# Función objetivo
def mean_cv_mse(X: pd.DataFrame, y: np.ndarray, k: int) -> float:
    model = LinearRegression()
    kf = KFold(n_splits=k, shuffle=True, random_state=42)

    mse_list = []

    for train_index, test_index in kf.split(X):
        X_train, X_test = X.iloc[train_index], X.iloc[test_index]
        y_train, y_test = y[train_index], y[test_index]

        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)

        mse = mean_squared_error(y_test, y_pred)
        mse_list.append(mse)

    return np.mean(mse_list)


# Función generadora de casos de uso
def generar_caso_de_uso_preparar_datos_0002():
    np.random.seed(None)  # aleatoriedad

    # Tamaño aleatorio
    n_samples = np.random.randint(50, 150)
    n_features = np.random.randint(2, 6)

    # Datos aleatorios
    X = pd.DataFrame(
        np.random.randn(n_samples, n_features),
        columns=[f'feature_{i}' for i in range(n_features)]
    )

    # Generar relación lineal + ruido
    coef = np.random.randn(n_features)
    y = X.values @ coef + np.random.randn(n_samples) * 0.5

    # k aleatorio (mínimo 2, máximo razonable)
    k = np.random.randint(2, 6)

    # Input
    input_data = {
        "X": X,
        "y": y,
        "k": k
    }

    # Output esperado
    output_data = mean_cv_mse(X, y, k)

    return input_data, output_data

input_data, output_data = generar_caso_de_uso_preparar_datos_0002()

print("=== INPUT ===")
print("X:")
print(input_data["X"].head())
print("\ny:", input_data["y"][:5])
print("\nk:", input_data["k"])

print("\n=== OUTPUT ===")
print("MSE promedio:", output_data)
