# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J42MEkpLH7b21kdkbIlxT4PNP_qYbpf5
"""

import pandas as pd
import numpy as np

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score


def optimizar_modelo(X_train, y_train, X_test, y_test):

    # Grid de hiperparámetros
    param_grid = {
        'n_estimators': [50, 100, 200],
        'max_depth': [None, 5, 10, 20],
        'min_samples_split': [2, 5, 10],
    }

    # Modelo base
    rf = RandomForestClassifier(random_state=42)

    # GridSearchCV
    grid_search = GridSearchCV(
        estimator=rf,
        param_grid=param_grid,
        scoring='accuracy',
        cv=5,
        n_jobs=-1,
        refit=True
    )

    # Entrenamiento
    grid_search.fit(X_train, y_train)

    # Mejor modelo
    mejor_modelo = grid_search.best_estimator_

    # Predicciones
    y_pred = mejor_modelo.predict(X_test)

    # Accuracy
    accuracy_test = round(
        accuracy_score(y_test, y_pred),
        4
    )

    # Importancia de variables
    importancias = mejor_modelo.feature_importances_

    # Ordenar de mayor a menor
    indices_ordenados = np.argsort(importancias)[::-1]

    df_importancia = pd.DataFrame({
        'feature': [f'feature_{i}' for i in indices_ordenados],
        'importancia': importancias[indices_ordenados].round(4)
    })

    # Resultado final
    return {
        'mejores_params': grid_search.best_params_,
        'accuracy_test': accuracy_test,
        'importancia': df_importancia
    }


# =====================================================
# EJEMPLO DE USO
# =====================================================

from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split

# Crear dataset de ejemplo
X, y = make_classification(
    n_samples=200,
    n_features=6,
    n_informative=4,
    random_state=42
)

# Dividir datos
X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.2,
    random_state=42
)

# Ejecutar función
resultado = optimizar_modelo(
    X_train,
    y_train,
    X_test,
    y_test
)

# Mostrar resultados
print("Mejores parámetros:")
print(resultado['mejores_params'])

print("\nAccuracy en test:")
print(resultado['accuracy_test'])

print("\nImportancia de features:")
print(resultado['importancia'])