# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J42MEkpLH7b21kdkbIlxT4PNP_qYbpf5
"""

import pandas as pd
from sklearn.linear_model import LogisticRegression

def entrenar_logistica(df, target_col):

    # Separar variables predictoras y objetivo
    X = df.drop(columns=[target_col])
    y = df[target_col]

    # Crear y entrenar modelo
    modelo = LogisticRegression()
    modelo.fit(X, y)

    # Realizar predicciones sobre los mismos datos
    predicciones = modelo.predict(X)

    # Retornar predicciones
    return predicciones


# =========================
# EJEMPLO DE USO
# =========================

import numpy as np

df = pd.DataFrame({
    "feat1": np.random.randn(20),
    "feat2": np.random.randn(20),
    "target": np.random.choice([0, 1], size=20)
})

resultado = entrenar_logistica(df, "target")

print("Predicciones:")
print(resultado)