# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Y-fdMvfGjlhP8RO7wj22gQhGZ-JEp1py
"""

import numpy as np
from sklearn.linear_model import LogisticRegression

def entrenar_logistica(df, target_col):
    # Separar X e y
    X = df.drop(columns=[target_col])
    y = df[target_col]

    # Entrenar modelo
    model = LogisticRegression()
    model.fit(X, y)

    # Predicciones sobre el mismo dataset
    preds = model.predict(X)

    return preds