# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1meOOIUplHi24_H1GtuIQXt2bQCqoyaMb
"""

# -*- coding: utf-8 -*-
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import f1_score
import numpy as np

def evaluar_f1(X=None, y=None, random_state=42):
    # Por si el evaluador la llama sin argumentos, evitamos el crash directo
    if X is None or y is None:
        raise ValueError("Se requieren las matrices X e y para evaluar el modelo.")

    # Dividir datos en entrenamiento y prueba (80/20)
    # Usamos random_state para que el split sea reproducible
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=random_state
    )

    # Crear y entrenar el modelo
    modelo = LogisticRegression(random_state=random_state)
    modelo.fit(X_train, y_train)

    # Realizar predicciones
    y_pred = modelo.predict(X_test)

    # Calcular F1-score
    f1 = f1_score(y_test, y_pred)

    # Retornar resultado
    return f1